# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:18:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/16 05:50:24 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = provider/rt_frontend_mlx_ctor.c \
	  provider/rt_frontend_mlx_provider.c \
	  screen/rt_screen_main.c \
	  rt_frontend_mlx_destroy.c \
	  rt_frontend_mlx_handoff.c \
	  rt_frontend_mlx_init.c \
	  rt_frontend_mlx_stop.c

include ../submodule.mk
