# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/10 13:34:17 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/18 01:59:12 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = error/rt_parse_err.c \
	  error/rt_parse_err_file.c \
	  error/rt_parse_err_print.c \
	  error/rt_parse_err_str.c \
	  error/rt_parse_errd.c \
	  error/rt_parse_errs.c \
	  error/rt_parse_is_err.c \
	  error/rt_parse_is_ok.c \
	  error/rt_parse_ok.c \
	  rt_parser_destroy.c \
	  rt_parser_init.c \
	  rt_parser_parse.c

include ../submodule.mk
