# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/10 13:34:17 by kiroussa          #+#    #+#              #
#    Updated: 2024/11/03 20:29:30 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = buffer/rt_parser_buffer_fill.c \
	  buffer/rt_parser_buffer_preproc.c \
	  buffer/rt_parser_buffer_sanitize.c \
	  error/rt_parse_err.c \
	  error/rt_parse_err_file.c \
	  error/rt_parse_err_print.c \
	  error/rt_parse_err_str.c \
	  error/rt_parse_errd.c \
	  error/rt_parse_errs.c \
	  error/rt_parse_is_err.c \
	  error/rt_parse_is_ok.c \
	  error/rt_parse_ok.c \
	  error/rt_parse_okd.c \
	  line/rt_parser_line_process.c \
	  primitive/strtod/rt_strtod.c \
	  primitive/strtod/rt_strtod_final.c \
	  primitive/strtod/rt_strtod_frac.c \
	  primitive/strtod/rt_strtod_midcheck.c \
	  primitive/strtod/rt_strtod_num.c \
	  primitive/rt_parser_prim_coords.c \
	  primitive/rt_parser_strprim.c \
	  rt_parser_destroy.c \
	  rt_parser_init.c \
	  rt_parser_parse.c

include ../submodule.mk
