# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:18:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/26 22:08:18 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = provider/rt_backend_dummy_ctor.c \
	  provider/rt_backend_dummy_provider.c \
	  rt_backend_dummy_destroy.c \
	  rt_backend_dummy_init.c \
	  rt_backend_dummy_render.c

include ../submodule.mk
