# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/10 13:34:17 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/12 02:19:54 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = parser

SRC = error/rt_parse_err.c \
	  error/rt_parse_err_file.c \
	  error/rt_parse_err_print.c \
	  error/rt_parse_err_str.c \
	  error/rt_parse_errd.c \
	  error/rt_parse_errs.c \
	  error/rt_parse_ok.c \
	  rt_parser.c

include ../submodule.mk
