# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/12 01:52:36 by kiroussa          #+#    #+#              #
#    Updated: 2024/11/15 05:27:03 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = args/rt_cli_opt_help.c \
	  args/rt_cli_opt_version.c \
	  args/rt_cli_parse.c \
	  args/rt_cli_parse_file_target.c \
	  parse/rt/rt_cli_parser_rt_init.c \
	  main.c \
	  rt_backend_init.c \
	  rt_frontend_init.c \
	  rt_parser_dump_state.c

IS_EXEC = 1

include ../submodule.mk
