# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:04:32 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/15 00:18:42 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC	=	backend/rt_devrl_backend_setup.c \
		backend/rt_devrl_load_backend.c \
		frontend/rt_devrl_frontend_setup.c \
	  	frontend/rt_devrl_load_frontend.c \
	  	rt_devrl_ctor.c \
		rt_devrl_dtor.c

include ../submodule.mk
