# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:04:32 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/13 03:25:59 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC =	log/rt_debug.c \
		log/rt_error.c \
		log/rt_info.c \
		log/rt_log.c \
		log/rt_trace.c \
		log/rt_vlog.c \
		log/rt_warning.c \
		rt_destroy.c \
		rt_init.c

include ../submodule.mk
