# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:04:32 by kiroussa          #+#    #+#              #
#    Updated: 2024/11/18 23:15:34 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC =	log/rt_debug.c \
		log/rt_eat_stdarg.c \
		log/rt_error.c \
		log/rt_info.c \
		log/rt_log.c \
		log/rt_trace.c \
		log/rt_vlog.c \
		log/rt_warn.c \
		render/backend/rt_move_camera.c \
		render/backend/rt_pixelisation.c \
		render/backend/rt_switch_cameras.c \
		render/registry/rt_backend_provider_find.c \
		render/registry/rt_backend_provider_register.c \
		render/registry/rt_backend_providers.c \
		render/registry/rt_frontend_provider_find.c \
		render/registry/rt_frontend_provider_register.c \
		render/registry/rt_frontend_providers.c \
		render/rt_backend_reload.c \
		render/rt_backend_handoff.c \
		render/rt_backend_switch.c \
		render/rt_frontend_reload.c \
		render/rt_frontend_switch.c \
		util/ft_syscall.c \
		util/rt_free_aligned.c \
		util/rt_malloc_aligned.c \
		util/rt_noop.c \
		util/rt_stat.c \
		rt_destroy.c \
		rt_exit.c \
		rt_init.c \
		rt_update.c \
		rt_resize.c

include ../submodule.mk
