# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:18:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/11/08 16:02:08 by yroussea         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = provider/rt_backend_raytracer_provider.c \
	  provider/rt_backend_raytracer_ctor.c \
	  rt_backend_raytracer_destroy.c \
	  rt_backend_raytracer_init.c \
	  rt_backend_raytracer_render.c	\
	  rt_backend_raytracer_ray_generator.c \
	  rt_backend_raytracer_find_obj_hit.c \
	  rt_backend_raytracer_shading.c \
	  utils/fmod.c	\
	  utils/solv_m3d.c	\
	  rt_objs/rt_backend_raytracer_checkerboard.c \
	  rt_objs/rt_backend_raytracer_sphere.c \
	  rt_objs/rt_backend_raytracer_planar.c \
	  rt_objs/rt_backend_raytracer_plane.c \
	  rt_objs/rt_backend_raytracer_cone_intersection.c \
	  rt_objs/rt_backend_raytracer_cone.c \
	  rt_objs/rt_backend_raytracer_cylinder_intersection.c \
	  rt_objs/rt_backend_raytracer_cylinder.c \
	  rt_objs/add_obj.c

include ../submodule.mk
