# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:18:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/26 02:02:30 by yroussea         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = provider/rt_backend_raytracer_provider.c \
	  provider/rt_backend_raytracer_ctor.c \
	  rt_backend_raytracer_destroy.c \
	  rt_backend_raytracer_init.c \
	  rt_backend_raytracer_render.c	\
	  rt_backend_raytracer_ray_generator.c \
	  rt_backend_raytracer_find_obj_hit.c \
	  rt_backend_raytracer_shading.c \
	  utils/fmod.c	\
	  utils/solv_m3d.c	\
	  rt_objs/plane.c \
	  rt_objs/sphere.c \
	  rt_objs/cylinder.c \
	  rt_objs/cone.c \
	  rt_objs/add_obj.c

include ../submodule.mk
