# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/13 00:18:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/10/18 20:18:47 by yroussea         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = provider/rt_backend_raytracer_provider.c \
	  provider/rt_backend_raytracer_ctor.c \
	  rt_backend_raytracer_destroy.c \
	  rt_backend_raytracer_init.c \
	  rt_backend_raytracer_render.c	\
	  rt_backend_raytracer_ray_generator.c \
	  rt_backend_raytracer_find_obj_hit.c \
	  rt_backend_raytracer_shading.c \
	  plane.c

include ../submodule.mk
